# Generated by Django 3.0.3 on 2020-11-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.TextField()),
                ('ClinicID', models.TextField()),
                ('Email', models.TextField()),
                ('Phone', models.TextField()),
                ('Appointments', models.TextField()),
                ('JobTitle', models.TextField()),
            ],
        ),
    ]
