# Generated by Django 3.0.3 on 2020-12-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='CategoryColor',
            field=models.CharField(blank=True, choices=[('#6665dd', 'Routine Check-Up'), ('#fe6140', 'Emergency'), ('#f28e26', 'Sick'), ('#46d5c5', 'Examination'), ('#0facff', 'Telemedicine')], max_length=10),
        ),
    ]
