# Generated by Django 3.0.3 on 2020-12-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201203_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='IsBlock',
            field=models.BooleanField(default=True),
        ),
    ]
