# Generated by Django 3.0.3 on 2020-12-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201211_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='CategoryColor',
            field=models.CharField(blank=True, choices=[('#46d5c5', 'Examination'), ('#6665dd', 'Routine Check-Up'), ('#fe6140', 'Emergency'), ('#0facff', 'Telemedicine'), ('#f28e26', 'Sick')], max_length=10),
        ),
    ]
