# Generated by Django 3.0.3 on 2020-12-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appointment_isblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='IsBlock',
            field=models.BooleanField(default=False),
        ),
    ]
