# Generated by Django 3.0.3 on 2020-12-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201206_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='docavailability',
            name='IsBlock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='docavailability',
            name='Subject',
            field=models.CharField(blank=True, max_length=96),
        ),
    ]
