# Generated by Django 3.0.3 on 2020-12-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201207_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='PatientID',
        ),
        migrations.RemoveField(
            model_name='docavailability',
            name='IsFree',
        ),
    ]
