# Generated by Django 3.0.3 on 2020-12-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201209_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='DoctorID',
        ),
        migrations.RemoveField(
            model_name='docavailability',
            name='DoctorID',
        ),
    ]
