# Generated by Django 3.0.3 on 2020-12-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_appointment_categorycolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='CategoryColor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='color',
            field=models.CharField(blank=True, choices=[('#ea7a57', 'Sick'), ('#00bdae', 'Emergency')], max_length=10),
        ),
    ]
