# Generated by Django 3.0.3 on 2020-12-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201210_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='color',
        ),
        migrations.AddField(
            model_name='appointment',
            name='CategoryColor',
            field=models.CharField(blank=True, choices=[('#1aaa55', 'Emergency'), ('#ea7a57', 'Sick')], max_length=10),
        ),
    ]
