# Generated by Django 3.0.3 on 2020-12-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201210_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='CategoryColor',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
