# Generated by Django 3.0.3 on 2020-12-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201210_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Category',
            new_name='CategoryColor',
        ),
    ]
