# Generated by Django 3.0.3 on 2020-12-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20201210_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='CategoryColor',
            field=models.CharField(blank=True, choices=[('#ea7a57', 'Sick'), ('#1aaa55', 'Emergency')], max_length=10),
        ),
    ]
