# Generated by Django 3.0.3 on 2020-12-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20201210_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='CategoryColor',
            field=models.CharField(blank=True, choices=[('#6665dd', 'Routine Check-Up'), ('#fe6140', 'Emergency'), ('#0facff', 'Consultation'), ('#46d5c5', 'Examination'), ('#f28e26', 'Sick')], max_length=10),
        ),
    ]
