# Generated by Django 3.0.3 on 2020-12-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20201210_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='docavailability',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='CategoryColor',
            field=models.CharField(blank=True, choices=[('#fe6140', 'Emergency'), ('#0facff', 'Telemedicine'), ('#46d5c5', 'Examination'), ('#f28e26', 'Sick'), ('#6665dd', 'Routine Check-Up')], max_length=10),
        ),
    ]
