# Generated by Django 3.0.3 on 2020-12-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20201211_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Email',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='docavailability',
            old_name='Email',
            new_name='Location',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='CategoryColor',
            field=models.CharField(blank=True, choices=[('#f28e26', 'Sick'), ('#6665dd', 'Routine Check-Up'), ('#fe6140', 'Emergency'), ('#46d5c5', 'Examination'), ('#0facff', 'Telemedicine')], max_length=10),
        ),
    ]
