# Generated by Django 3.0.3 on 2020-12-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20201211_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='CategoryColor',
            field=models.CharField(blank=True, choices=[('#0facff', 'Telemedicine'), ('#6665dd', 'Routine Check-Up'), ('#fe6140', 'Emergency'), ('#46d5c5', 'Examination'), ('#f28e26', 'Sick')], max_length=10),
        ),
    ]
